# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 5) do

  create_table "locations", :force => true do |t|
    t.column "name",        :string
    t.column "latitude",    :decimal, :precision => 15, :scale => 10
    t.column "longitude",   :decimal, :precision => 15, :scale => 10
    t.column "country",     :string
    t.column "time_zone",   :string
    t.column "restriction", :string
    t.column "loc_type",    :string
    t.column "reference",   :string
  end

  add_index "locations", ["name"], :name => "index_locations_on_name"
  add_index "locations", ["latitude"], :name => "index_locations_on_latitude"
  add_index "locations", ["longitude"], :name => "index_locations_on_longitude"

end
